# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radiant-layouts-extension}
  s.version = "0.9.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Dirk Kelly"]
  s.date = %q{2010-08-30}
  s.description = %q{TODO: Provides extensions to standard layouts, including nesting of layouts within each other and sharing radiant layouts with rails controllers}
  s.email = %q{dk@squaretalent.com}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "app/models/rails_page.rb",
     "app/views/layouts/radiant.html.haml",
     "config/routes.rb",
     "layouts_extension.rb",
     "lib/nested_layouts.rb",
     "lib/nested_layouts/tags.rb",
     "lib/share_layouts.rb",
     "lib/share_layouts/helper.rb",
     "lib/share_layouts/radiant_layouts.rb",
     "lib/tasks/layouts_extension_tasks.rake",
     "radiant-layouts-extension.gemspec",
     "spec/controllers/nested_layouts_spec.rb",
     "spec/controllers/share_layouts_spec.rb",
     "spec/datasets/nested_layouts_dataset.rb",
     "spec/datasets/share_layouts_dataset.rb",
     "spec/helpers/share_layouts_helper_spec.rb",
     "spec/lib/nested_layouts/tags_spec.rb",
     "spec/lib/share_layouts_extension_spec.rb",
     "spec/models/rails_page_spec.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/squaretalent/radiant-layouts-extension}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{TODO: Provides extensions to standard layouts, including nesting and sharing}
  s.test_files = [
    "spec/controllers/nested_layouts_spec.rb",
     "spec/controllers/share_layouts_spec.rb",
     "spec/datasets/nested_layouts_dataset.rb",
     "spec/datasets/share_layouts_dataset.rb",
     "spec/helpers/share_layouts_helper_spec.rb",
     "spec/lib/nested_layouts/tags_spec.rb",
     "spec/lib/share_layouts_extension_spec.rb",
     "spec/models/rails_page_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 1.3.2"])
      s.add_development_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_development_dependency(%q<cucumber-rails>, [">= 0.3.2"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0.4.3"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_development_dependency(%q<webrat>, [">= 0.10.3"])
    else
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<rspec-rails>, [">= 1.3.2"])
      s.add_dependency(%q<cucumber>, [">= 0.8.5"])
      s.add_dependency(%q<cucumber-rails>, [">= 0.3.2"])
      s.add_dependency(%q<database_cleaner>, [">= 0.4.3"])
      s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
      s.add_dependency(%q<webrat>, [">= 0.10.3"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<rspec-rails>, [">= 1.3.2"])
    s.add_dependency(%q<cucumber>, [">= 0.8.5"])
    s.add_dependency(%q<cucumber-rails>, [">= 0.3.2"])
    s.add_dependency(%q<database_cleaner>, [">= 0.4.3"])
    s.add_dependency(%q<ruby-debug>, [">= 0.10.3"])
    s.add_dependency(%q<webrat>, [">= 0.10.3"])
  end
end

